### POST
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "pen",
  "price": 22.222
}


### GET

GET http://localhost:8080/api/products/1
Accept: application/json


### GET

GET http://localhost:8080/api/products
Accept: application/json

### PATCH

PATCH http://localhost:8080/api/products
Content-Type: application/json

{
  "id": 1,
  "name": "hi",
  "price": 220
}

###DELETE

DELETE http://localhost:8080/api/products/1
Accept: application/json

